# Uffizzi extension
x-uffizzi:
  ingress:
    service: guestbook
    port: 8080
  continuous_previews:
    deploy_preview_when_pull_request_is_opened: true
    delete_preview_when_pull_request_is_closed: true
    deploy_preview_when_image_tag_is_created: true
    delete_preview_after: 24h
    share_to_github: true

services:
  redis:
    image: redis:latest
    deploy:
      resources:
        limits:
          memory: 125M

  guestbook:
    build: .
    environment:
      REDIS_HOST: localhost
    deploy:
      resources:
        limits:
          memory: 125M
